### ISSUE TITLE
Explore trademark issues to determine whether a name change is required

### ISSUE THREAD

**Issue by binford2k** [OpenPuppetProject/planning#5]
By default we cannot use the name `OpenPuppet` because Puppet by Perforce [owns the wordmark "puppet"](https://tsdr.uspto.gov/#caseNumber=86897996&caseSearchType=US_APPLICATION&caseType=DEFAULT&searchType=statusSearch) in context of software, DevOps, configuration management, etc.

We are requesting an irrevocable license to use the wordmark “puppet” only within context of the OpenPuppet project.

* We will promote only the name OpenPuppet and will not use branding, logos, phrasing, etc. from Puppet.
* We are requesting the right to build the package OpenPuppet containing the command line tool, service names, etc of puppet and related such as puppetdb.
* We are willing to sign an agreement to those terms (after legal review, of course.)

If we're able to get this license, it will help keep the community unfragmented as the paths, commands, and options won't change and so tooling / modules will be more likely to be compatible with both. It will also make it easier for Puppet by Perforce to benefit from our work.

**Comment by binford2k** [comment]
Current status: initial request to Perforce Legal was denied. Tzvika is going to try to explain the case better.

**Comment by yakatz** [comment]
Naming discussion: #9

**Comment by anarcat** [comment]
in today's town hall, the Perforce folks explicitly said that a Puppet fork would not be allowed to use the name Puppet, implicitly saying that Perforce would start legal action against organisations or people doing this.

I think, therefore, that this issue is moot and should be closed in favor of the discussion to find a new name (#9), as it is pretty clear a new name is required, unless someone fancies going into a legal battle with investment firms.
